name: Android-Чтосмотреть-分享阅读
on:
  workflow_dispatch:
  schedule:
    - cron: 7 8,11 * * *
  watch:
    types: started
  repository_dispatch:
    types: bean_change
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        zq_cookie: ${{ secrets.ZQ_COOKIE11 }}
        zq_cookie2: ${{ secrets.ZQ_COOKIE21 }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【zq_share_read】'
        if: env.zq_cookie
        run: |
          node zq_share_read.js
        env:
          zq_cookie: ${{ secrets.ZQ_COOKIE11 }} ${{ secrets.ZQ_COOKIE21 }}
          
