name: Android-Чтосмотреть-阅读奖励
on:
  workflow_dispatch:
  schedule:
    - cron: 1 3,11 * * *
  watch:
    types: started
  repository_dispatch:
    types: bean_change
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        zqerciboxbody: ${{ secrets.ZQERCIBOXBODY }}
        zqerciboxbody2: ${{ secrets.ZQERCIBOXBOD2 }}
        zqerciboxbody3: ${{ secrets.ZQERCIBOXBOD3 }}
        zqerciboxbody4: ${{ secrets.ZQERCIBOXBOD4 }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【zq_5_60】'
        if: env.zqerciboxbody
        run: |
          node zq_5_60.js
        env:
          zqerciboxbodyy: ${{ secrets.ZQBOXBODY }}
          
      - name: '运行 【zq_5_60】'
        if: env.zqerciboxbody2
        run: |
          node zq_5_60.js
        env:
          zqerciboxbodyy: ${{ secrets.ZQBOXBODY2 }}
        
